name: Build and deploy ASP.Net Core app to Azure Web App - LittleGenius-LAB

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore
        working-directory: ./backend

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./backend

      - name: Publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp" --no-build
        working-directory: ./backend

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F1CF1C9F7543498ABE599A7B86C7AB4C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CA0D3670FA8B49F6854F3A69091853CF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_640D47CB77CC483FAE0B2B3BC695D4C3 }}

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'LittleGenius-LAB'
          slot-name: 'Production'
          package: .
