name: Build and deploy ASP.Net Core app to Azure Web App - LittleGenius-LAB

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_PATH: './backend

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: ${{ env.PROJECT_PATH }}

      - name: dotnet publish
        run: dotnet publish -c Release -o publish
        working-directory: ${{ env.PROJECT_PATH }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.PROJECT_PATH }}/publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AEFEE1D147B24C02A75DAE2E5929BC2E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E583A9B244F4427E99AB829CA2F96D83 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C56197229FB04725977984D3B28ECA8D }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'LittleGenius-LAB'
          slot-name: 'Production'
          package: .
